rplidar_node:
  ros__parameters:

    ############################
    ## Serial
    ############################
    
    serial_port: /dev/lidar
    serial_baudrate: 115200

    ############################
    ## Frame
    ############################

    frame_id: lidar_link

    inverted: false

    angle_compensate: true

    scan_mode: Standard

    ############################
    ## Scan
    ############################

    scan_frequency: 10.0

    max_distance: 16.0

    min_distance: 0.15

    ############################
    ## Health
    ############################

    auto_reconnect: true